"use client";

import { useEffect, useRef, useState } from "react";
import type { Lang, T } from "@/lib/i18n";

type Hit = { url: string; title: string; excerpt: string };

/** Full-text search powered by Pagefind (build-time static index, zero
 *  server). The index is generated by `pagefind --site out` after next
 *  build; in dev without the index this component degrades gracefully.
 *  pagefind.js is a pure ES module with named exports (no global). */
export default function SearchBox({ lang, tt }: { lang: Lang; tt: T }) {
  const [q, setQ] = useState("");
  const [hits, setHits] = useState<Hit[]>([]);
  const [open, setOpen] = useState(false);
  const pf = useRef<any>(null);
  const timer = useRef<ReturnType<typeof setTimeout>>();
  const boxRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    (async () => {
      try {
        const url = "/pagefind/pagefind.js"; // variable: skip TS module check
        const mod: any = await import(/* webpackIgnore: true */ url);
        await mod.init();
        pf.current = mod;
      } catch { /* index absent in dev — search stays dormant */ }
    })();
  }, []);

  useEffect(() => {
    const onClick = (e: MouseEvent) => {
      if (!boxRef.current?.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("click", onClick);
    return () => document.removeEventListener("click", onClick);
  }, []);

  const run = (value: string) => {
    setQ(value);
    clearTimeout(timer.current);
    if (!value.trim() || !pf.current) { setHits([]); return; }
    timer.current = setTimeout(async () => {
      const res = await pf.current.debouncedSearch(value);
      if (!res) return;
      const data = await Promise.all(res.results.slice(0, 8).map((r: any) => r.data()));
      setHits(data.map((d: any) => ({
        url: d.url,
        title: (d.meta?.title || d.url).split(" · ")[0],
        excerpt: d.excerpt,
      })));
      setOpen(true);
    }, 180);
  };

  return (
    <div className="search" ref={boxRef}>
      <input
        type="search"
        value={q}
        onChange={(e) => run(e.target.value)}
        onFocus={() => hits.length && setOpen(true)}
        placeholder={tt.searchPlaceholder}
        aria-label={tt.searchPlaceholder}
      />
      {open && q.trim() && (
        <div className="search-results" role="listbox">
          {hits.length === 0 && <div className="search-empty">{tt.noResults}</div>}
          {hits.map((h) => (
            <a key={h.url} href={h.url} className="search-hit" role="option">
              <span className="hit-title">{h.title}</span>
              <span className="hit-excerpt"
                dangerouslySetInnerHTML={{ __html: h.excerpt }} />
            </a>
          ))}
        </div>
      )}
    </div>
  );
}
